# Generated by Django 2.0.2 on 2018-02-28 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 28, 7, 38, 52, 659939), verbose_name='Created On')),
                ('type', models.CharField(choices=[('get', 'GET'), ('save', 'SAVE')], max_length=5, verbose_name='Type')),
            ],
        ),
    ]
