# Generated by Django 2.0.2 on 2018-02-28 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerDemo', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='A coupon', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 7, 51, 57, 832983), verbose_name='Created On'),
        ),
    ]
