# Generated by Django 2.0.2 on 2018-03-04 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerDemo', '0003_auto_20180228_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 8, 52, 18, 239774), verbose_name='Created On'),
        ),
    ]
